### ISSUE TITLE
Issue for peer to peer code review 4 -01-22

### ISSUE THREAD

**Issue by memelopez** [Reem-lab/AwesomeBooks#1]
https://github.com/Reem-lab/AwesomeBooks/blob/a335724acc6f8fdbd9010cc02572d65ee2de7ad8/script.js#L14

when writing the tag names for 'create element' try using lower case

**Comment by hendridg** [comment]
# Great job @Reem-lab 

- Congratulations on making the form save on local storage 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)
